In [230]:
import pandas as pd
import numpy as np

In [231]:
worldcup = pd.read_csv('WorldCups.csv')

In [232]:
worldcup["Host Country"] = worldcup["Year"].map(str) + ' ' + worldcup["Country"]

In [233]:
worldcup['Winner']=np.where(worldcup['Winner'] == 'Germany FR','Germany', worldcup['Winner'])
worldcup['Runners-Up']=np.where(worldcup['Runners-Up'] == 'Germany FR','Germany', worldcup['Runners-Up'])
worldcup['Third']=np.where(worldcup['Third'] == 'Germany FR','Germany', worldcup['Third'])
worldcup['Fourth']=np.where(worldcup['Fourth'] == 'Germany FR','Germany', worldcup['Fourth'])

In [234]:
worldcup['rank'] = np.where(worldcup['Country'] == worldcup['Winner'],1\
                            ,np.where(worldcup['Country'] == worldcup['Runners-Up'],2\
                            ,np.where(worldcup['Country'] == worldcup['Third'],3\
                            ,np.where(worldcup['Country'] == worldcup['Fourth'],4,0))))

In [235]:
worldrank = pd.read_csv('World Rank.csv')
missingrank = pd.read_csv('Missing Ranks.csv')

In [236]:
df = worldcup
df1 = worldrank
df2 = missingrank

In [237]:
df2.index = df.loc[df['rank']==0].index

In [238]:
df.loc[df['rank'] == 0, 'rank'] = df2['rank']

In [239]:
df = df.merge(df1,on='Year')

In [240]:
df['Different'] = df['world rank'] - df['rank']

In [241]:
df['Difficulty'] = df['Different'] / df['rank']

In [242]:
df

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance,Host Country,rank,world rank,Different,Difficulty
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549,1930 Uruguay,1,2,1,1.000000
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363,1934 Italy,1,1,0,0.000000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.7,1938 France,8,30,22,2.750000
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246,1950 Brazil,2,2,0,0.000000
4,1954,Switzerland,Germany,Hungary,Austria,Uruguay,140,16,26,768.607,1954 Switzerland,8,17,9,1.125000
5,1958,Sweden,Brazil,Sweden,France,Germany,126,16,35,819.81,1958 Sweden,2,7,5,2.500000
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172,1962 Chile,3,17,14,4.666667
7,1966,England,England,Germany,Portugal,Soviet Union,89,16,32,1.563.135,1966 England,1,1,0,0.000000
8,1970,Mexico,Brazil,Italy,Germany,Uruguay,95,16,32,1.603.975,1970 Mexico,8,29,21,2.625000
9,1974,Germany,Germany,Netherlands,Poland,Brazil,97,16,38,1.865.753,1974 Germany,1,1,0,0.000000
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791,1978 Argentina,1,3,2,2.000000
11,1982,Spain,Italy,Germany,Poland,France,146,24,52,2.109.723,1982 Spain,8,17,9,1.125000
12,1986,Mexico,Argentina,Germany,France,Belgium,132,24,52,2.394.031,1986 Mexico,8,9,1,0.125000
13,1990,Italy,Germany,Argentina,Italy,England,115,24,52,2.516.215,1990 Italy,3,2,-1,-0.333333
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538,1994 USA,16,48,32,2.000000
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100,1998 France,1,1,0,0.000000
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197,2002 Korea/Japan,4,27,23,5.750000
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439,2006 Germany,3,8,5,1.666667
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856,2010 South Africa,16,37,21,1.312500
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810,2014 Brazil,4,7,3,0.750000

In [243]:
df = df[['Year','Host Country','Winner','Runners-Up','Third','Fourth','rank'\
               ,'world rank','Different','Difficulty']]

In [244]:
df

,Year,Host Country,Winner,Runners-Up,Third,Fourth,rank,world rank,Different,Difficulty
0,1930,1930 Uruguay,Uruguay,Argentina,USA,Yugoslavia,1,2,1,1.000000
1,1934,1934 Italy,Italy,Czechoslovakia,Germany,Austria,1,1,0,0.000000
2,1938,1938 France,Italy,Hungary,Brazil,Sweden,8,30,22,2.750000
3,1950,1950 Brazil,Uruguay,Brazil,Sweden,Spain,2,2,0,0.000000
4,1954,1954 Switzerland,Germany,Hungary,Austria,Uruguay,8,17,9,1.125000
5,1958,1958 Sweden,Brazil,Sweden,France,Germany,2,7,5,2.500000
6,1962,1962 Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,3,17,14,4.666667
7,1966,1966 England,England,Germany,Portugal,Soviet Union,1,1,0,0.000000
8,1970,1970 Mexico,Brazil,Italy,Germany,Uruguay,8,29,21,2.625000
9,1974,1974 Germany,Germany,Netherlands,Poland,Brazil,1,1,0,0.000000
10,1978,1978 Argentina,Argentina,Netherlands,Brazil,Italy,1,3,2,2.000000
11,1982,1982 Spain,Italy,Germany,Poland,France,8,17,9,1.125000
12,1986,1986 Mexico,Argentina,Germany,France,Belgium,8,9,1,0.125000
13,1990,1990 Italy,Germany,Argentina,Italy,England,3,2,-1,-0.333333
14,1994,1994 USA,Brazil,Italy,Sweden,Bulgaria,16,48,32,2.000000
15,1998,1998 France,France,Brazil,Croatia,Netherlands,1,1,0,0.000000
16,2002,2002 Korea/Japan,Brazil,Germany,Turkey,Korea Republic,4,27,23,5.750000
17,2006,2006 Germany,Italy,France,Germany,Portugal,3,8,5,1.666667
18,2010,2010 South Africa,Spain,Netherlands,Germany,Uruguay,16,37,21,1.312500
19,2014,2014 Brazil,Germany,Argentina,Netherlands,Brazil,4,7,3,0.750000

In [245]:
df.to_csv('Finding3.csv')